# Generated by Django 6.0.4 on 2026-04-14 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='cotent',
            field=models.TextField(default='', verbose_name='CONTENT'),
        ),
        migrations.AddField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFIED DATE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='PUBLISHED DATE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='TITLE'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
